# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-17 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text_editor',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='text_editor',
            name='text',
        ),
        migrations.AddField(
            model_name='text_editor',
            name='source_lang',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='text_editor',
            name='source_text',
            field=models.CharField(default=b'', max_length=2000),
        ),
        migrations.AddField(
            model_name='text_editor',
            name='submission_id',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
