# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-17 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20170317_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text_Editor',
        ),
    ]
