# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-22 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0005_auto_20170522_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, default=b'')),
                ('bio', models.TextField(blank=True, default=b'')),
                ('phone', models.CharField(blank=True, default=b'', max_length=20)),
                ('city', models.CharField(blank=True, default=b'', max_length=100)),
                ('country', models.CharField(blank=True, default=b'', max_length=100)),
                ('organization', models.CharField(blank=True, default=b'', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
