# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-23 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_auto_20170522_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text_Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.CharField(default=b'', max_length=2000)),
                ('source_lang', models.CharField(default=b'', max_length=20)),
                ('submission_id', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='KerbUser',
        ),
    ]
